# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    # env:
    #   STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

    strategy:
      matrix:
        # TODO support node 18
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --ignore-scripts
    # TODO bring this back down to moderate
    # Fail an audit only if the results include a vulnerability with a level of critical:
    - run: npm audit --audit-level=critical
    - run: npm run build
    - run: npm run lint
    - run: npm run type-coverage
    - name: validate cli can be invoked
      run: dist/seed-project help
    # FIXME enable these once you've written your first test
    # - run: npm run test
    # - run: npm run codecov
    # - run: npm run mutation-test
